data:
  train_lmdb_dir: './data/feature_labels_2023/lmdb_synthdata_len10s' 
  test_lmdb_dir: './data/feature_labels_2023/lmdb_synthdata_len10s' 
  ref_files_dir: 'C:/data/2024DCASE_data/metadata_dev' # label files
  norm_file: "C:/26'interspeech/Solution_on_3D_SELD/data/feature_labels_2023/mic_wts" # normalization file
  test_segment_len: 100 
  train_segment_len: 100
  segment_len: 100
  batch_size: 32
  train_ignore: 'enh' # or None. 'enh' means ignore the enhancement data
  test_ignore: 'enh'

model:
  type: 'seddist_nopool' # my_model7, myexperiment.py
  criterion: 'BCE+MSPE'
  loss_weight: [0.1, 1.0]
  in_channel: 10
  in_dim: 64
  out_dim: 39
  # 'early_manifold'
  pre-train: True
  pre-train_model: './output/my_experiment14/checkpoints\checkpoint_epoch337_step92001.pth'

train:
  train_num_workers: 0
  test_num_workers: 0
  lr: 0.001
  nb_steps: 100000

result:
  log_output_path: './output/my_experiment14/train4.log'
  log_interval: 100
  checkpoint_output_dir: './output/my_experiment14/checkpoints'
  dcase_output_dir: './output/my_experiment14/results'
  frontend_weight_plot_path: './output/my_experiment14/frontend_weights4.png'

test:
  test_output_dir: './output/my_experiment14/test_outputs.log'
  test_output_csv_dir: './output/my_experiment14/test_csvs'
  snr_db: 20
  same_noise_across_channels: False
